### ISSUE TITLE
BBC Food Site

### ISSUE THREAD

**Issue by jane-t** [seethroughdev/obsidian-recipe-grabber#19] opened 2024-01-04 17:18 UTC
When using the standard template with the BBC food site,  the ingredients come in fine but the Method is blank although it does put in the list markers.

Here is an example recipe https://www.bbc.co.uk/food/recipes/chargrilled_halloumi_09010

I can see the instructions in the json section in the page source,  so I suspect I just need to change the template, but am not sure where to start.

**Comment by seethroughdev** [comment] 2024-01-04 20:49
I can reproduce your issue, thanks for letting me know. I will make sure to add a fix for this in the next release. In the meantime, you can manually add the fix yourself by doing this:

- Go into `Recipe Grabber Settings`
- Go to `Recipe Template`
- Find `### Instructions`
- Directly underneath that, you will see some code that looks like this:

```
{{#each recipeInstructions}}
{{#if this.itemListElement}}
#### {{{this.name}}}
{{#each this.itemListElement}}
- {{{this.text}}}
{{/each}}
{{else}}
- {{{this.text}}}
{{/if}}
{{/each}}
```

If you replace that entire section with:

```
{{#each recipeInstructions}}
{{#if this.itemListElement}}
#### {{{this.name}}}
{{#each this.itemListElement}}
- {{{this.text}}}
{{/each}}
{{else if this.text}}
- {{{this.text}}}
{{else}}
- {{{this}}}
{{/if}}
{{/each}}
```

instead, it should work as expected. And if something breaks, you can just press the `Reset to default` button and try again.

I will hopefully get the fix out in the next day or so.

**Comment by jane-t** [comment] 2024-01-04 22:16
Thanks for the quick reply, that worked well.  Non standard standards are always fun to work with.

**Closed** 2024-01-05 17:41 UTC
