### ISSUE TITLE
Not working with diacritics

### ISSUE THREAD

**Issue by Gnopps** [seethroughdev/obsidian-recipe-grabber#15] opened 2023-11-22 22:35 UTC
Thanks for developing this plugin! 

The plugin seems to work well also with non-English recipes. However, diacritical marks aren't captured correctly. 

"ä" becomes ``&auml;``, "å" becomes ``&aring``, etc. in edit mode. The characters display correctly in reading-mode. Would it possible to import the native characters rather than these HTML-characters?

Edit mode:
![image](https://github.com/seethroughdev/obsidian-recipe-grabber/assets/16313148/9f955073-a79b-4d62-ab7f-52cda9d55fc9)

Reading mode:
![image](https://github.com/seethroughdev/obsidian-recipe-grabber/assets/16313148/0405a0fc-204c-4846-b1b8-e012dc30dcb7)

Original:
![image](https://github.com/seethroughdev/obsidian-recipe-grabber/assets/16313148/41b1f31b-2398-430b-bb80-f7bc304af59e)

Example recipe (in Swedish): https://www.ica.se/recept/laxgryta-med-purjolok-majs-och-citron-713481/

**Comment by seethroughdev** [comment] 2023-11-23 20:05
Thanks for the note here. Unfortunately, that is the expected behavior as the json schema includes the escaped html: 

<img width="322" alt="Screenshot 2023-11-23 at 12 05 23 PM" src="https://github.com/seethroughdev/obsidian-recipe-grabber/assets/203779/ac94ebef-b0c7-40df-afda-8034dd8db32f">

So in Preview mode, you'll get the rendered html, but not in edit. Sorry about that!

**Comment by seethroughdev** [comment] 2023-11-24 21:01
Yes, that does sound frustrating. Since html is already escaped in the json, we'd have to actually render the each line as html, then convert it back to strings without escaping.

I'm not sure if this is the overall best default behavior for the plugin yet. But in the meantime, I could add a settings option called `Allow potentially unsafe html` and manually do this for each string.

**Comment by seethroughdev** [comment] 2024-01-04 21:08
So sorry that i forgot to make a release for this feature! I added it back in, and will get it out in the next day or two! Keep you updated.

**Comment by seethroughdev** [comment] 2024-01-05 17:42
You now have a setting to prevent escaping html, which should make edit pages the same as the view pages.

Updated in https://github.com/seethroughdev/obsidian-recipe-grabber/releases/tag/0.18.0 and verified. Thanks again for taking the time.

**Comment by Gnopps** [comment] 2024-01-06 09:28
Thanks for the update! Perhaps it would also be a good idea to add info in the setting or doc about why it is a risk to enable the new setting?

**Comment by Flxp49** [comment] 2024-01-15 07:31
> There is now a setting to prevent escaping html, which should make edit pages the same as the view pages.
> 
> Updated in https://github.com/seethroughdev/obsidian-recipe-grabber/releases/tag/0.18.0 and verified. Thanks again for taking the time.

@seethroughdev I've noticed only the `recipeInstructions` includes the html entites. We could just pass those texts through an html decoder that returns replaces the entites with the proper characters and leaves the rest as it is, this would also get rid of the settings option. Thoughts?

**Comment by seethroughdev** [comment] 2024-01-15 23:38
I like your thoughts here @Flxp49 . I would normally prefer not to change source text, but i can't see why users would care if its going to markdown.

What do you think about a no lib option for decoding like this? It was also used in [another PR](https://github.com/seethroughdev/obsidian-recipe-grabber/pull/20).

```
function decodeHtml(html) {
    const txt = document.createElement("textarea");
    txt.innerHTML = html;
    return txt.value;
}
```

**Comment by Flxp49** [comment] 2024-01-16 05:44
Oh yes this would work, perfect. No need for a dependency and its not gonna be a lot of text anyway so performance drop will be negligible. Good stuff from @derekthecool.

**Comment by seethroughdev** [comment] 2024-06-05 17:51
This finally works as expected in https://github.com/seethroughdev/obsidian-recipe-grabber/releases/tag/0.21.0. Confirmed with your url. Closing for now, feel free to reopen if you see any issue!

**Closed by seethroughdev** 2024-06-05 17:51 UTC
